# Generated by Django 4.0.4 on 2022-04-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('painting', models.ImageField(upload_to='')),
                ('price', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
    ]
