# Generated by Django 4.0.4 on 2022-05-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintingShop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting',
            name='painting',
        ),
        migrations.AddField(
            model_name='painting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='painting',
            name='size',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='painting',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='painting',
            name='price',
            field=models.CharField(default='Jaka cena??', max_length=200),
        ),
    ]
